# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
from pathlib import Path
applicant_data_df = pd.read_csv(Path('Resources/applicants_data.csv'))

# Review the DataFrame
applicant_data_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [4]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['EIN','NAME'])

# Review the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [5]:
# Create a list of categorical variables 
categorical_variables = ["AFFILIATION", "USE_CASE","ORGANIZATION","CLASSIFICATION","SPECIAL_CONSIDERATIONS"]

# Display the categorical variables list
categorical_variables

['AFFILIATION',
 'USE_CASE',
 'ORGANIZATION',
 'CLASSIFICATION',
 'SPECIAL_CONSIDERATIONS']

In [6]:
# Create a OneHotEncoder instance
enc = OneHotEncoder()

In [7]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])
encoded_data

<34299x88 sparse matrix of type '<class 'numpy.float64'>'
	with 171495 stored elements in Compressed Sparse Row format>

In [8]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(encoded_data.toarray(), columns=enc.get_feature_names())

# Review the DataFrame
encoded_df

,x0_CompanySponsored,x0_Family/Parent,x0_Independent,x0_National,x0_Other,x0_Regional,x1_CommunityServ,x1_Heathcare,x1_Other,x1_Preservation,...,x3_C7000,x3_C7100,x3_C7120,x3_C7200,x3_C7210,x3_C8000,x3_C8200,x3_C8210,x4_N,x4_Y
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [9]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([encoded_df,applicant_data_df[['STATUS','ASK_AMT','IS_SUCCESSFUL']]], axis=1)

# Review the Dataframe
encoded_df

,x0_CompanySponsored,x0_Family/Parent,x0_Independent,x0_National,x0_Other,x0_Regional,x1_CommunityServ,x1_Heathcare,x1_Other,x1_Preservation,...,x3_C7200,x3_C7210,x3_C8000,x3_C8200,x3_C8210,x4_N,x4_Y,STATUS,ASK_AMT,IS_SUCCESSFUL
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590,1
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692,1
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34295,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34296,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34297,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
34298,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,36500179,0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [10]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL'].values

# Display a sample of y
y

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [11]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=['IS_SUCCESSFUL'])

# Review the features DataFrame
X

,x0_CompanySponsored,x0_Family/Parent,x0_Independent,x0_National,x0_Other,x0_Regional,x1_CommunityServ,x1_Heathcare,x1_Other,x1_Preservation,...,x3_C7120,x3_C7200,x3_C7210,x3_C8000,x3_C8200,x3_C8210,x4_N,x4_Y,STATUS,ASK_AMT
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34295,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34296,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34297,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34298,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,36500179

### Step 6: Split the features and target sets into training and testing datasets.

In [12]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [13]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [14]:
# Define the the number of inputs (features) to the model
number_input_features = X_train_scaled.shape[1]

# Review the number of features
number_input_features

90

In [15]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [16]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 = 100

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

100

In [17]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  50

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

50

In [18]:
# Create the Sequential model instance
nn = Sequential()

In [19]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, activation="relu", input_dim=number_input_features))

In [20]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu", input_dim=hidden_nodes_layer1))

In [21]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons, activation="sigmoid"))

In [22]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 100)               9100
_________________________________________________________________
dense_1 (Dense)              (None, 50)                5050
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 51
=================================================================
Total params: 14,201
Trainable params: 14,201
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [23]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [24]:
# Fit the model using 50 epochs and the training data
nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 740us/step - loss: 0.6049 - accuracy: 0.6928
Epoch 2/50
804/804 [==============================] - 1s 764us/step - loss: 0.5894 - accuracy: 0.6976
Epoch 3/50
804/804 [==============================] - 1s 756us/step - loss: 0.5882 - accuracy: 0.6957
Epoch 4/50
804/804 [==============================] - 1s 755us/step - loss: 0.5852 - accuracy: 0.6993
Epoch 5/50
804/804 [==============================] - 1s 801us/step - loss: 0.5848 - accuracy: 0.7002
Epoch 6/50
804/804 [==============================] - 1s 770us/step - loss: 0.5843 - accuracy: 0.7002
Epoch 7/50
804/804 [==============================] - 1s 868us/step - loss: 0.5829 - accuracy: 0.7018
Epoch 8/50
804/804 [==============================] - 1s 823us/step - loss: 0.5827 - accuracy: 0.7011
Epoch 9/50
804/804 [==============================] - 1s 764us/step - loss: 0.5821 - accuracy: 0.7012
Epoch 10/50
804/804 [==============================] - 1s 754us/step - loss: 0.5823 - accuracy: 0.7007
Epoch 11/50
804/804 [==============================] - 1s 829us/step - loss: 0.5813 - accuracy: 0.7014
Epoch 12/50
804/804 [==============================] - 1s 796us/step - loss: 0.5810 - accuracy: 0.7027
Epoch 13/50
804/804 [==============================] - 1s 683us/step - loss: 0.5810 - accuracy: 0.7037
Epoch 14/50
804/804 [==============================] - 1s 696us/step - loss: 0.5810 - accuracy: 0.7033
Epoch 15/50
804/804 [==============================] - 1s 686us/step - loss: 0.5802 - accuracy: 0.7030
Epoch 16/50
804/804 [==============================] - 1s 667us/step - loss: 0.5797 - accuracy: 0.7025
Epoch 17/50
804/804 [==============================] - 1s 720us/step - loss: 0.5796 - accuracy: 0.7041
Epoch 18/50
804/804 [==============================] - 1s 760us/step - loss: 0.5794 - accuracy: 0.7041
Epoch 19/50
804/804 [==============================] - 1s 678us/step - loss: 0.5792 - accuracy: 0.7039
Epoch 20/50
804/804 [==============================] - 1s 706us/step - loss: 0.5794 - accuracy: 0.7043
Epoch 21/50
804/804 [==============================] - 1s 694us/step - loss: 0.5788 - accuracy: 0.7045
Epoch 22/50
804/804 [==============================] - 1s 724us/step - loss: 0.5786 - accuracy: 0.7044
Epoch 23/50
804/804 [==============================] - 1s 705us/step - loss: 0.5785 - accuracy: 0.7030
Epoch 24/50
804/804 [==============================] - 1s 744us/step - loss: 0.5783 - accuracy: 0.7052
Epoch 25/50
804/804 [==============================] - 1s 778us/step - loss: 0.5780 - accuracy: 0.7062
Epoch 26/50
804/804 [==============================] - 1s 774us/step - loss: 0.5775 - accuracy: 0.7055
Epoch 27/50
804/804 [==============================] - 1s 750us/step - loss: 0.5773 - accuracy: 0.7058
Epoch 28/50
804/804 [==============================] - 1s 696us/step - loss: 0.5777 - accuracy: 0.7056
Epoch 29/50
804/804 [==============================] - 1s 773us/step - loss: 0.5775 - accuracy: 0.7039
Epoch 30/50
804/804 [==============================] - 1s 760us/step - loss: 0.5774 - accuracy: 0.7060
Epoch 31/50
804/804 [==============================] - 1s 865us/step - loss: 0.5765 - accuracy: 0.7056
Epoch 32/50
804/804 [==============================] - 1s 738us/step - loss: 0.5770 - accuracy: 0.7058
Epoch 33/50
804/804 [==============================] - 1s 759us/step - loss: 0.5768 - accuracy: 0.7055
Epoch 34/50
804/804 [==============================] - 1s 712us/step - loss: 0.5767 - accuracy: 0.7067
Epoch 35/50
804/804 [==============================] - 1s 758us/step - loss: 0.5765 - accuracy: 0.7059
Epoch 36/50
804/804 [==============================] - 1s 727us/step - loss: 0.5765 - accuracy: 0.7065
Epoch 37/50
804/804 [==============================] - 1s 710us/step - loss: 0.5765 - accuracy: 0.7063
Epoch 38/50
804/804 [==============================] - 1s 683us/step - loss: 0.5759 - accuracy: 0.7067
Epoch 39/50
804/804 [==============================] - 1s 825us/step - loss: 0.5762 - accuracy: 0.7066
Epoch 40/50
804/804 [==============================] - 1s 930us/step - loss: 0.5757 - accuracy: 0.7067
Epoch 41/50
804/804 [==============================] - 1s 861us/step - loss: 0.5764 - accuracy: 0.7070
Epoch 42/50
804/804 [==============================] - 1s 900us/step - loss: 0.5762 - accuracy: 0.7068
Epoch 43/50
804/804 [==============================] - 1s 693us/step - loss: 0.5757 - accuracy: 0.7058
Epoch 44/50
804/804 [==============================] - 1s 702us/step - loss: 0.5756 - accuracy: 0.7067
Epoch 45/50
804/804 [==============================] - 1s 698us/step - loss: 0.5762 - accuracy: 0.7072
Epoch 46/50
804/804 [==============================] - 1s 673us/step - loss: 0.5753 - accuracy: 0.7057
Epoch 47/50
804/804 [==============================] - 1s 678us/step - loss: 0.5753 - accuracy: 0.7068
Epoch 48/50
804/804 [==============================] - 1s 671us/step - loss: 0.5755 - accuracy: 0.7063
Epoch 49/50
804/804 [==============================] - 1s 811us/step - loss: 0.5751 - accuracy: 0.7055
Epoch 50/50
804/804 [==============================] - 1s 715us/step - loss: 0.5752 - accuracy: 0.7063

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [25]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5839 - accuracy: 0.7094
Loss: 0.583875298500061, Accuracy: 0.7093877792358398

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [26]:
# Set the model's file path
file_path = Path("Resources/AlphabetSoup.h5")
# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [27]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

90

In [28]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [29]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 100

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

100

In [30]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [31]:
# First hidden layer
hidden_nodes_layer1_A1


# Output layer
number_output_neurons_A1


# Check the structure of the model
nn_A1

In [32]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [33]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 492us/step - loss: 7.8969 - accuracy: 0.0596
Epoch 2/50
804/804 [==============================] - 0s 456us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 3/50
804/804 [==============================] - 0s 424us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 4/50
804/804 [==============================] - 0s 420us/step - loss: 7.8969 - accuracy: 0.0596
Epoch 5/50
804/804 [==============================] - 0s 420us/step - loss: 7.8969 - accuracy: 0.0596
Epoch 6/50
804/804 [==============================] - 0s 451us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 7/50
804/804 [==============================] - 0s 461us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 8/50
804/804 [==============================] - 0s 515us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 9/50
804/804 [==============================] - 0s 385us/step - loss: 7.8969 - accuracy: 0.0596
Epoch 10/50
804/804 [==============================] - 0s 390us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 11/50
804/804 [==============================] - 0s 385us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 12/50
804/804 [==============================] - 0s 393us/step - loss: 7.8969 - accuracy: 0.0596
Epoch 13/50
804/804 [==============================] - 0s 409us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 14/50
804/804 [==============================] - 0s 385us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 15/50
804/804 [==============================] - 0s 410us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 16/50
804/804 [==============================] - 0s 420us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 17/50
804/804 [==============================] - 0s 386us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 18/50
804/804 [==============================] - 0s 454us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 19/50
804/804 [==============================] - 0s 441us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 20/50
804/804 [==============================] - 0s 520us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 21/50
804/804 [==============================] - 0s 426us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 22/50
804/804 [==============================] - 0s 418us/step - loss: 7.8969 - accuracy: 0.0596
Epoch 23/50
804/804 [==============================] - 0s 389us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 24/50
804/804 [==============================] - 0s 419us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 25/50
804/804 [==============================] - 0s 447us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 26/50
804/804 [==============================] - 0s 386us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 27/50
804/804 [==============================] - 0s 408us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 28/50
804/804 [==============================] - 0s 406us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 29/50
804/804 [==============================] - 0s 418us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 30/50
804/804 [==============================] - 0s 409us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 31/50
804/804 [==============================] - 0s 385us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 32/50
804/804 [==============================] - 0s 447us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 33/50
804/804 [==============================] - 0s 449us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 34/50
804/804 [==============================] - 0s 484us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 35/50
804/804 [==============================] - 0s 476us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 36/50
804/804 [==============================] - 0s 405us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 37/50
804/804 [==============================] - 0s 401us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 38/50
804/804 [==============================] - 0s 451us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 39/50
804/804 [==============================] - 0s 461us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 40/50
804/804 [==============================] - 0s 444us/step - loss: 7.8969 - accuracy: 0.0596
Epoch 41/50
804/804 [==============================] - 0s 403us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 42/50
804/804 [==============================] - 0s 442us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 43/50
804/804 [==============================] - 0s 400us/step - loss: 7.8969 - accuracy: 0.0596
Epoch 44/50
804/804 [==============================] - 0s 442us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 45/50
804/804 [==============================] - 0s 394us/step - loss: 7.8969 - accuracy: 0.0596
Epoch 46/50
804/804 [==============================] - 0s 384us/step - loss: 7.8969 - accuracy: 0.0596
Epoch 47/50
804/804 [==============================] - 0s 390us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 48/50
804/804 [==============================] - 0s 388us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 49/50
804/804 [==============================] - 0s 411us/step - loss: 7.8968 - accuracy: 0.0596
Epoch 50/50
804/804 [==============================] - 0s 378us/step - loss: 7.8968 - accuracy: 0.0596

#### Alternative Model 2

In [34]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

90

In [35]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [36]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 100

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

100

In [37]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [39]:
# First hidden layer
hidden_nodes_layer1_A2

# Output layer
number_output_neurons_A2

# Check the structure of the model
nn_A2

In [38]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [40]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train)

804/804 [==============================] - 0s 456us/step - loss: 7.8968 - accuracy: 0.0596

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [43]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5839 - accuracy: 0.7094
Loss: 0.583875298500061, Accuracy: 0.7093877792358398

In [44]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 7.8359 - accuracy: 0.0575
Loss: 7.835906505584717, Accuracy: 0.057492710649967194

In [45]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)
# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 7.8359 - accuracy: 0.0575
Loss: 7.835906505584717, Accuracy: 0.057492710649967194

### Step 3: Save each of your alternative models as an HDF5 file.

In [46]:
# Set the file path for the first alternative model
file_path = Path("Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [47]:
# Set the file path for the second alternative model
file_path = Path("Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn_A2.save(file_path)